Through this task we can uderstand different encoding methods such as Label encoding and one hot encoding. These methods are used to transform categorical values to numerical values that can be used in machine learning algorithms.

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [18]:
data = {
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female'],
    'AppointmentType': ['General', 'Emergency', 'Consultation', 'General', 'Emergency'],
    'City': ['Kottayam', 'Kochi', 'Calicut', 'Kochi', 'Kottayam']
}

df = pd.DataFrame(data)

print("Original Dataset:")
display(df)

Original Dataset:

   Gender AppointmentType      City
0    Male         General  Kottayam
1  Female       Emergency     Kochi
2  Female    Consultation   Calicut
3    Male         General     Kochi
4  Female       Emergency  Kottayam

In [3]:
#Inspect Dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           5 non-null      object
 1   AppointmentType  5 non-null      object
 2   City             5 non-null      object
dtypes: object(3)
memory usage: 252.0+ bytes

In [4]:
display(df.head())

   Gender AppointmentType      City
0    Male         General  Kottayam
1  Female       Emergency     Kochi
2  Female    Consultation   Calicut
3    Male         General     Kochi
4  Female       Emergency  Kottayam

In [5]:
display(df.describe(include='all'))

        Gender AppointmentType      City
count        5               5         5
unique       2               3         3
top     Female         General  Kottayam
freq         3               2         2

All the columns in the given dataset is contains categorical values. There is no missing value present.Encoding is necessary to prepare the dataset for further machine learning techniques and algorithms.

In [6]:
label_df = df.copy()

In [7]:
#label encoding
le = LabelEncoder()

In [8]:

label_df['Gender'] = le.fit_transform(label_df['Gender'])
label_df['AppointmentType'] = le.fit_transform(label_df['AppointmentType'])
label_df['City'] = le.fit_transform(label_df['City'])

print("Label Encoded Dataset:")
display(label_df)

Label Encoded Dataset:

   Gender  AppointmentType  City
0       1                2     2
1       0                1     1
2       0                0     0
3       1                2     1
4       0                1     2

Label encoding converts the category values into unique integer value .For example in the gender column 1 is assigned to all the male values while 0 is assigned to all the female values. It is suitable for ordinal category. It use low memory and also have lower computational cost.

In [9]:
print("Label Encoded Dataset:")
display(label_df)

Label Encoded Dataset:

   Gender  AppointmentType  City
0       1                2     2
1       0                1     1
2       0                0     0
3       1                2     1
4       0                1     2

In [10]:
#Display Encoding Mapping

In [11]:
print("Gender Mapping:")
print(dict(zip(le.classes_,
               le.transform(le.classes_))))

Gender Mapping:
{'Calicut': np.int64(0), 'Kochi': np.int64(1), 'Kottayam': np.int64(2)}

In [12]:
print("\nAppointmentType Mapping:")
print(dict(zip(le.classes_,
               le.transform(le.classes_))))

AppointmentType Mapping:
{'Calicut': np.int64(0), 'Kochi': np.int64(1), 'Kottayam': np.int64(2)}

In [13]:
print("\nCity Mapping:")
print(dict(zip(le.classes_,
               le.transform(le.classes_))))

City Mapping:
{'Calicut': np.int64(0), 'Kochi': np.int64(1), 'Kottayam': np.int64(2)}

In [14]:
#One-Hot Encoding
onehot_df = pd.get_dummies(df)

In [15]:
print("One-Hot Encoded Dataset:")
display(onehot_df)

One-Hot Encoded Dataset:

,Gender_Female,Gender_Male,AppointmentType_Consultation,AppointmentType_Emergency,AppointmentType_General,City_Calicut,City_Kochi,City_Kottayam
0,False,True,False,False,True,False,False,True
1,True,False,False,True,False,False,True,False
2,True,False,True,False,False,True,False,False
3,False,True,False,False,True,False,True,False
4,True,False,False,True,False,False,False,True

In one hot encoding a it creates separate binary columns for each category, where 1 represents the presence of a category and 0 represents its absence. It is preferred for nominal categorical data. This can lead to higher number of columns . There is also high usage of memory and higher computation cost.

In [16]:
#comparative analysis
print("Original Dataset Shape:", df.shape)
print("Label Encoded Shape:", label_df.shape)
print("One-Hot Encoded Shape:", onehot_df.shape)

Original Dataset Shape: (5, 3)
Label Encoded Shape: (5, 3)
One-Hot Encoded Shape: (5, 8)

In [17]:
comparison = pd.DataFrame({
    'Dataset': ['Original', 'Label Encoded', 'One-Hot Encoded'],
    'Rows': [df.shape[0], label_df.shape[0], onehot_df.shape[0]],
    'Columns': [df.shape[1], label_df.shape[1], onehot_df.shape[1]]
})
display(comparison)

           Dataset  Rows  Columns
0         Original     5        3
1    Label Encoded     5        3
2  One-Hot Encoded     5        8

Label encoding maintains the original dataset size but it may create misleading ordinal relationship between categories. While one hot encoding avoid this issue it increases the size of the dataset . The nature of the categorical dataset decides which encoding method to use. For the given dataset the most preferred encoding method is one hot encoding. because all are nominal categories and there is no ranking among the values. It provides a more accurate representation of the dataset to the machine learning algorithm.