The dataset contains information about the medical appointment process. The problem comes when the patient misses the scheduled appointment.The data is analyzed to explain and solve the different patterns shown. This is to to better understand why there is a growth in patients missing their scedule

In [29]:
import pandas as pd
import numpy as np

In [30]:
df=df = pd.read_csv('/content/KaggleV2-May-2016.csv')

In [31]:
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [32]:
df.tail()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
110522,2.572134e+12,5651768,F,2016-05-03T09:15:35Z,2016-06-07T00:00:00Z,56,MARIA ORTIZ,0,0,0,0,0,1,No
110523,3.596266e+12,5650093,F,2016-05-03T07:27:33Z,2016-06-07T00:00:00Z,51,MARIA ORTIZ,0,0,0,0,0,1,No
110524,1.557663e+13,5630692,F,2016-04-27T16:03:52Z,2016-06-07T00:00:00Z,21,MARIA ORTIZ,0,0,0,0,0,1,No
110525,9.213493e+13,5630323,F,2016-04-27T15:09:23Z,2016-06-07T00:00:00Z,38,MARIA ORTIZ,0,0,0,0,0,1,No
110526,3.775115e+14,5629448,F,2016-04-27T13:30:56Z,2016-06-07T00:00:00Z,54,MARIA ORTIZ,0,0,0,0,0,1,No

In [33]:
print("Dataset Shape:", df.shape)

Dataset Shape: (110527, 14)

In [34]:
print(df.columns)

Index(['PatientId', 'AppointmentID', 'Gender', 'ScheduledDay',
       'AppointmentDay', 'Age', 'Neighbourhood', 'Scholarship', 'Hipertension',
       'Diabetes', 'Alcoholism', 'Handcap', 'SMS_received', 'No-show'],
      dtype='object')

In [35]:
df.dtypes

PatientId         float64
AppointmentID       int64
Gender             object
ScheduledDay       object
AppointmentDay     object
Age                 int64
Neighbourhood      object
Scholarship         int64
Hipertension        int64
Diabetes            int64
Alcoholism          int64
Handcap             int64
SMS_received        int64
No-show            object
dtype: object

The above shows the different columns and their datatypes. We will encode teh categorical columns so that the text data can be converted into a language that is understandable by the machine learning models.

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PatientId       110527 non-null  float64
 1   AppointmentID   110527 non-null  int64
 2   Gender          110527 non-null  object
 3   ScheduledDay    110527 non-null  object
 4   AppointmentDay  110527 non-null  object
 5   Age             110527 non-null  int64
 6   Neighbourhood   110527 non-null  object
 7   Scholarship     110527 non-null  int64
 8   Hipertension    110527 non-null  int64
 9   Diabetes        110527 non-null  int64
 10  Alcoholism      110527 non-null  int64
 11  Handcap         110527 non-null  int64
 12  SMS_received    110527 non-null  int64
 13  No-show         110527 non-null  object
dtypes: float64(1), int64(8), object(5)
memory usage: 11.8+ MB

In [37]:
#Count Missing Values
df.isnull().sum()
print("Total Missing Values:")
print(df.isnull().sum().sum())

Total Missing Values:
0

Here we can see that there is no missing value in the given medical appointment dataset. Hence we do not need to handle any missing value.

In [38]:
df.describe()

,PatientId,AppointmentID,Age,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received
count,1.105270e+05,1.105270e+05,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000
mean,1.474963e+14,5.675305e+06,37.088874,0.098266,0.197246,0.071865,0.030400,0.022248,0.321026
std,2.560949e+14,7.129575e+04,23.110205,0.297675,0.397921,0.258265,0.171686,0.161543,0.466873
min,3.921784e+04,5.030230e+06,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.172614e+12,5.640286e+06,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.173184e+13,5.680573e+06,37.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,9.439172e+13,5.725524e+06,55.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,9.999816e+14,5.790484e+06,115.000000,1.000000,1.000000,1.000000,1.000000,4.000000,1.000000

In [39]:
numerical_cols = df.select_dtypes(include=['int64','float64'])

print("Mean")
print(numerical_cols.mean())

print("\nMedian")
print(numerical_cols.median())

print("\nStandard Deviation")
print(numerical_cols.std())

Mean
PatientId        1.474963e+14
AppointmentID    5.675305e+06
Age              3.708887e+01
Scholarship      9.826558e-02
Hipertension     1.972459e-01
Diabetes         7.186479e-02
Alcoholism       3.039981e-02
Handcap          2.224796e-02
SMS_received     3.210256e-01
dtype: float64

Median
PatientId        3.173184e+13
AppointmentID    5.680573e+06
Age              3.700000e+01
Scholarship      0.000000e+00
Hipertension     0.000000e+00
Diabetes         0.000000e+00
Alcoholism       0.000000e+00
Handcap          0.000000e+00
SMS_received     0.000000e+00
dtype: float64

Standard Deviation
PatientId        2.560949e+14
AppointmentID    7.129575e+04
Age              2.311020e+01
Scholarship      2.976748e-01
Hipertension     3.979213e-01
Diabetes         2.582651e-01
Alcoholism       1.716856e-01
Handcap          1.615427e-01
SMS_received     4.668727e-01
dtype: float64

In [40]:
#Encode Categorical Variables
categorical_cols = df.select_dtypes(include=['object']).columns
print(categorical_cols)
for col in categorical_cols:
    df[col] = pd.factorize(df[col])[0]

df.head()

Index(['Gender', 'ScheduledDay', 'AppointmentDay', 'Neighbourhood', 'No-show'], dtype='object')

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,0,0,0,62,0,0,1,0,0,0,0,0
1,5.589978e+14,5642503,1,1,0,56,0,0,0,0,0,0,0,0
2,4.262962e+12,5642549,0,2,0,62,1,0,0,0,0,0,0,0
3,8.679512e+11,5642828,0,3,0,8,2,0,0,0,0,0,0,0
4,8.841186e+12,5642494,0,4,0,56,0,0,1,1,0,0,0,0

In [41]:
df.dtypes

PatientId         float64
AppointmentID       int64
Gender              int64
ScheduledDay        int64
AppointmentDay      int64
Age                 int64
Neighbourhood       int64
Scholarship         int64
Hipertension        int64
Diabetes            int64
Alcoholism          int64
Handcap             int64
SMS_received        int64
No-show             int64
dtype: object

In [42]:
print(df.shape)

(110527, 14)

In [43]:
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,0,0,0,62,0,0,1,0,0,0,0,0
1,5.589978e+14,5642503,1,1,0,56,0,0,0,0,0,0,0,0
2,4.262962e+12,5642549,0,2,0,62,1,0,0,0,0,0,0,0
3,8.679512e+11,5642828,0,3,0,8,2,0,0,0,0,0,0,0
4,8.841186e+12,5642494,0,4,0,56,0,0,1,1,0,0,0,0

The medical appointment dataset was analysed to study the structure and different data types present. The categorical values were encoded.The dataset is converted so that it is suitable for future data anlytics and machine learning tasks.