In [16]:
# Import required libraries
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [17]:
# Load dataset
df = pd.read_csv('/content/fitness_activity_100+_preprocess (1).csv')

The dataset has been loaded successfully.

In [18]:
# Display first few rows
df.head()

  User_ID  Steps_Per_Day  Calories_Burned  Workout_Minutes
0      U1           9270              581               91
1      U2          17795              735              119
2      U3           2860              341               17
3      U4           7390              381              117
4      U5          15418              449               84

In [19]:
# Dataset information
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User_ID          100 non-null    object
 1   Steps_Per_Day    100 non-null    int64
 2   Calories_Burned  100 non-null    int64
 3   Workout_Minutes  100 non-null    int64
dtypes: int64(3), object(1)
memory usage: 3.3+ KB
None

The column User_ID is of the type object which all other columns are numerical.From the statistical summary we obtained the mean standard deviationa etc.

In [20]:
# Statistical summary
print(df.describe())

       Steps_Per_Day  Calories_Burned  Workout_Minutes
count     100.000000       100.000000       100.000000
mean     9992.390000       542.620000        69.030000
std      4551.436736       209.950681        32.540093
min      2189.000000       184.000000        15.000000
25%      5929.750000       377.250000        40.250000
50%     10107.500000       561.500000        70.500000
75%     13303.750000       727.750000       100.250000
max     17920.000000       899.000000       119.000000

In [21]:
#Select Features for Scaling
features = ['Steps_Per_Day', 'Calories_Burned', 'Workout_Minutes']
X = df[features]

In [22]:
# Standard Scaling
standard_scaler = StandardScaler()
X_standard = standard_scaler.fit_transform(X)
standard_df = pd.DataFrame(
    X_standard,
    columns=features
)
print("Standard Scaled Data")
standard_df.head()

Standard Scaled Data

   Steps_Per_Day  Calories_Burned  Workout_Minutes
0      -0.159517         0.183726         0.678568
1       1.722954         0.920927         1.543380
2      -1.574958        -0.965159        -1.607006
3      -0.574654        -0.773678         1.481608
4       1.198071        -0.448161         0.462365

In [23]:
# Min-Max Scaling
minmax_scaler = MinMaxScaler()
X_minmax = minmax_scaler.fit_transform(X)
minmax_df = pd.DataFrame(
    X_minmax,
    columns=features
)
print("Min-Max Scaled Data")
minmax_df.head()

Min-Max Scaled Data

   Steps_Per_Day  Calories_Burned  Workout_Minutes
0       0.450130         0.555245         0.730769
1       0.992054         0.770629         1.000000
2       0.042655         0.219580         0.019231
3       0.330621         0.275524         0.980769
4       0.840951         0.370629         0.663462

In [24]:
compare = pd.concat(
    [
        X.head(),
        standard_df.head(),
        minmax_df.head()
    ],
    axis=1
)
compare

,Steps_Per_Day,Calories_Burned,Workout_Minutes,Steps_Per_Day,Calories_Burned,Workout_Minutes,Steps_Per_Day,Calories_Burned,Workout_Minutes
0,9270,581,91,-0.159517,0.183726,0.678568,0.450130,0.555245,0.730769
1,17795,735,119,1.722954,0.920927,1.543380,0.992054,0.770629,1.000000
2,2860,341,17,-1.574958,-0.965159,-1.607006,0.042655,0.219580,0.019231
3,7390,381,117,-0.574654,-0.773678,1.481608,0.330621,0.275524,0.980769
4,15418,449,84,1.198071,-0.448161,0.462365,0.840951,0.370629,0.663462

In [25]:
#Statistical Comparison
print("Standard scaler statistics")
print(standard_df.describe())
print("\nmin-max scaler statistics")
print(minmax_df.describe())

Standard scaler statistics
       Steps_Per_Day  Calories_Burned  Workout_Minutes
count   1.000000e+02     1.000000e+02     1.000000e+02
mean    1.199041e-16    -3.552714e-17    -3.108624e-17
std     1.005038e+00     1.005038e+00     1.005038e+00
min    -1.723127e+00    -1.716721e+00    -1.668778e+00
25%    -8.971028e-01    -7.916293e-01    -8.889031e-01
50%     2.541833e-02     9.037891e-02     4.540262e-02
75%     7.312069e-01     8.862208e-01     9.642652e-01
max     1.750557e+00     1.705998e+00     1.543380e+00

min-max scaler statistics
       Steps_Per_Day  Calories_Burned  Workout_Minutes
count     100.000000       100.000000       100.000000
mean        0.496052         0.501566         0.519519
std         0.289329         0.293637         0.312886
min         0.000000         0.000000         0.000000
25%         0.237795         0.270280         0.242788
50%         0.503369         0.527972         0.533654
75%         0.706551         0.760490         0.819712
max         1.000000         1.000000         1.000000

The features were transformed using StandardScaler to have mean as 0 and standard deviation as 1. It retains the effect of outliers. The Minmaxscaler converted all the values to the range 0 to 1. It copressed the values so that it lies between a selected range which is 0 to 1. Both of these techniques turned out to be effective for scaling.